---
sidebar: sidebar 
permalink: reference-instance-types.html 
keywords: BlueXP classification, installation, deployment, instance, virtual machine, cpu, ram, memory, disk, capacity 
summary: 'O software de classificação BlueXP  deve ser executado em um host que atenda a requisitos específicos do sistema operacional, requisitos de RAM, requisitos de software etc. Ao implantar a classificação do BlueXP  na nuvem, recomendamos que você use um sistema com as caraterísticas "grandes" para obter a funcionalidade completa.' 
---
= Tipos de instância de classificação BlueXP  compatíveis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O software de classificação BlueXP  deve ser executado em um host que atenda a requisitos específicos do sistema operacional, requisitos de RAM, requisitos de software etc. Ao implantar a classificação do BlueXP  na nuvem, recomendamos que você use um sistema com as caraterísticas "grandes" para obter a funcionalidade completa.

Você pode implantar a classificação BlueXP  em um sistema com menos CPUs e menos RAM, mas há algumas limitações ao usar esses sistemas menos poderosos. link:concept-cloud-compliance.html["Saiba mais sobre essas limitações"^].

Nas tabelas a seguir, se o sistema marcado como "padrão" não estiver disponível na região onde você está instalando a classificação BlueXP , o próximo sistema na tabela será implantado.



== Tipos de instância da AWS

[cols="20,30,25"]
|===
| Tamanho do sistema | Especificações | Tipo de instância 


| Extra grande | 32 CPUs, 128 GB de RAM, 1 TIB GP3 SSD | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.8xlarge"^] (predefinição) 


| Grande | 16 CPUs, 64 GB de RAM, 500 GiB SSD | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.4xlarge"^] (predefinição) m6a.4xlarge m5a.4xlarge m5,4xlarge m4,4xlarge 


| Média | 8 CPUs, 32 GB de RAM, 200 GiB SSD | https://aws.amazon.com/ec2/instance-types/m6i/["m6i.2xlarge"^] (predefinição) m6a.2xlarge m5a.2xlarge m5,2xlarge m4,2xlarge 


| Pequeno | 8 CPUs, 16 GB de RAM, 100 GiB SSD | https://aws.amazon.com/ec2/instance-types/c6a/["c6a.2xlarge"^] (predefinição) c5a.2xlarge c5,2xlarge c4,2xlarge 
|===


== Tipos de instância do Azure

[cols="20,30,25"]
|===
| Tamanho do sistema | Especificações | Tipo de instância 


| Extra grande | 32 CPUs, 128 GB de RAM, disco do sistema operacional (2.048 GiB, taxa de transferência mínima de 250 MB/s) e disco de dados (SSD de 1 TIB, taxa de transferência mínima de 750 MB/s) | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dv3-series["Standard_D32_v3"^] (predefinição) 


| Grande | 16 CPUs, 64 GB de RAM, 500 GiB SSD | https://learn.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series#dsv3-series["Standard_D16s_v3"^] (predefinição) 
|===


== Tipos de instância do GCP

[cols="20,30,25"]
|===
| Tamanho do sistema | Especificações | Tipo de instância 


| Grande | 16 CPUs, 64 GB de RAM, 500 GiB SSD | https://cloud.google.com/compute/docs/general-purpose-machines#n2_machines["n2-padrão-16"^] (padrão) n2d-standard-16 n1-standard-16 
|===