---
sidebar: sidebar 
permalink: task-test-linux-system.html 
keywords: cloud compliance, bluexp, data sense, get started, deploy, bluexp classification, cloud compliance access, compliance, on-premises, linux, test linux system, docker, podman, ubuntu, rhel, dark site, bluexp 
summary: Antes de instalar a classificação BlueXP  manualmente em um host Linux, você pode executar um script no host para verificar se todos os pré-requisitos estão em vigor para instalar a classificação BlueXP . Você pode executar esse script em um host Linux em sua rede ou em um host Linux na nuvem. O host pode ser conetado à internet, ou o host pode residir em um site que não tem acesso à internet. 
---
= Verifique se o seu host Linux está pronto para instalar a classificação BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de instalar a classificação BlueXP  manualmente em um host Linux, opcionalmente execute um script no host para verificar se todos os pré-requisitos estão em vigor para instalar a classificação BlueXP . Você pode executar esse script em um host Linux em sua rede ou em um host Linux na nuvem. O host pode ser conetado à internet, ou o host pode residir em um site que não tem acesso à internet (um _site escuro_).

Há também um script de teste pré-requisito que faz parte do script de instalação de classificação BlueXP . O script descrito aqui é projetado especificamente para usuários que desejam verificar o host Linux independentemente de executar o script de instalação de classificação BlueXP .



== Como começar

Você executará as seguintes tarefas.

. Opcionalmente, instale um conetor BlueXP  se você ainda não tiver um instalado. Você pode executar o script de teste sem ter um conetor instalado, mas o script verifica a conetividade entre o conetor e a máquina host de classificação BlueXP  - por isso, é recomendável que você tenha um conetor.
. Prepare a máquina host e verifique se ela atende a todos os requisitos.
. Ative o acesso de saída à Internet a partir da máquina host de classificação BlueXP .
. Verifique se todas as portas necessárias estão ativadas em todos os sistemas.
. Baixe e execute o script de teste pré-requisito.




== Crie um conetor

É necessário um conetor BlueXP  antes de poder instalar e utilizar a classificação BlueXP . Você pode, no entanto, executar o script pré-requisitos sem um conetor.

Você pode https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-on-prem.html["Instale o conetor no local"^] em um host Linux em sua rede ou em um host Linux na nuvem. Alguns usuários que planejam instalar a classificação do BlueXP  no local também podem optar por instalar o conetor no local.

Para criar um conetor no ambiente do provedor de nuvem, consulte https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["Criando um conetor na AWS"^] https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Criando um conetor no Azure"^] , https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Criando um conetor no GCP"^] ou .

Você precisará do endereço IP ou do nome do host do sistema do conetor ao executar o script de pré-requisitos. Você terá esta informação se você instalou o conetor em suas instalações. Se o conetor for implantado na nuvem, você poderá encontrar essas informações no console do BlueXP : Clique no ícone Ajuda, selecione *suporte* e clique em *conetor BlueXP *.



== Verifique os requisitos do host

O software de classificação BlueXP  deve ser executado em um host que atenda a requisitos específicos do sistema operacional, requisitos de RAM, requisitos de software etc.

* A classificação BlueXP  não é suportada em um host que é compartilhado com outros aplicativos - o host deve ser um host dedicado.
* Ao criar o sistema host em suas instalações, você pode escolher entre esses tamanhos de sistema, dependendo do tamanho do conjunto de dados que você planeja fazer a verificação de classificação do BlueXP .
+
[cols="17,17,27,31"]
|===
| Tamanho do sistema | CPU | RAM (a memória swap deve ser desativada) | Disco 


| * Extra grande * | 32 CPUs | 128 GB DE RAM  a| 
** SSD TIB de 1 GB ligado / ou 100 GiB disponível em /opt
** 895 GiB disponível em /var/lib/docker
** 5 GiB em /tmp
** *Para Podman, 5 GB em /tmp*
** *Para Podman, 30 GB em /var/tmp*




| * Grande * | 16 CPUs | 64 GB DE RAM  a| 
** SSD de 500 GiB em / ou 100 GiB disponível em /opt
** 395 GiB disponível em /var/lib/docker ou Podman /var/lib/containers ou Podman /var/lib/containers
** 5 GiB em /tmp
** *Para Podman, 5 GB em /tmp*
** *Para Podman, 30 GB em /var/tmp*


|===
* Ao implantar uma instância de computação na nuvem para sua instalação de classificação do BlueXP , recomendamos um sistema que atenda aos requisitos "grandes" do sistema acima:
+
** *Tipo de instância do Amazon Elastic Compute Cloud (Amazon EC2)*: Recomendamos "m6i.4xlarge". link:reference-instance-types.html#aws-instance-types["Consulte tipos de instâncias adicionais da AWS"^].
** *Tamanho da VM do Azure*: Recomendamos "Standard_D16s_v3". link:reference-instance-types.html#azure-instance-types["Consulte tipos de instância adicionais do Azure"^].
** *Tipo de máquina GCP*: Recomendamos "n2-standard-16". link:reference-instance-types.html#gcp-instance-types["Consulte tipos de instância adicionais do GCP"^].


* *Permissões de pasta UNIX*: As seguintes permissões mínimas UNIX são necessárias:
+
[cols="25,25"]
|===
| Pasta | Permissões mínimas 


| /tmp | `rwxrwxrwt` 


| /opt | `rwxr-xr-x` 


| /var/lib/docker | `rwx------` 


| /usr/lib/systemd/system | `rwxr-xr-x` 
|===
* *Sistema operacional*:
+
** Os seguintes sistemas operacionais requerem o uso do mecanismo de contentor Docker:
+
*** Red Hat Enterprise Linux versão 7,8 e 7,9
*** Ubuntu 22,04 (requer classificação BlueXP  versão 1,23 ou superior)
*** Ubuntu 24,04 (requer classificação BlueXP  versão 1,23 ou superior)


** Os seguintes sistemas operacionais requerem o uso do motor de contentores Podman, e eles exigem a classificação BlueXP  versão 1,30 ou superior:
+
*** Red Hat Enterprise Linux versão 8,8, 9,0, 9,1, 9,2, 9,3, 9,4




* *Red Hat Subscription Management*: O host deve estar registrado no Red Hat Subscription Management. Se não estiver registrado, o sistema não poderá acessar repositórios para atualizar o software necessário de 3rd partes durante a instalação.
* * Software adicional*: Você deve instalar o seguinte software no host antes de instalar a classificação BlueXP :
+
** Dependendo do sistema operacional que você estiver usando, você precisará instalar um dos motores de contentor:
+
*** Docker Engine versão 19.3.1 ou superior. https://docs.docker.com/engine/install/["Veja as instruções de instalação"^].
*** Podman versão 4 ou superior. Para instalar o Podman, digite (`sudo yum install podman netavark -y`).






* Python versão 3,6 ou superior. https://www.python.org/downloads/["Veja as instruções de instalação"^].
+
** *Considerações de NTP*: A NetApp recomenda configurar o sistema de classificação BlueXP  para usar um serviço de protocolo de tempo de rede (NTP). O tempo deve ser sincronizado entre o sistema de classificação BlueXP  e o sistema de conetores BlueXP .
** *Considerações sobre o Firewalld*: Se você estiver planejando usar `firewalld`, recomendamos que você a ative antes de instalar a classificação do BlueXP . Execute os seguintes comandos para configurar `firewalld` de modo que seja compatível com a classificação BlueXP :
+
....
firewall-cmd --permanent --add-service=http
firewall-cmd --permanent --add-service=https
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=8080/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload
....
+
Se você estiver planejando usar hosts de classificação BlueXP  adicionais como nós de scanner (em um modelo distribuído), adicione essas regras ao seu sistema principal neste momento:

+
....
firewall-cmd --permanent --add-port=2377/tcp
firewall-cmd --permanent --add-port=7946/udp
firewall-cmd --permanent --add-port=7946/tcp
firewall-cmd --permanent --add-port=4789/udp
....
+
Observe que você deve reiniciar o Docker ou o Podman sempre que ativar ou atualizar `firewalld` as configurações.







== Ative o acesso de saída à Internet a partir da classificação BlueXP 

A classificação BlueXP  requer acesso de saída à Internet. Se a sua rede virtual ou física utilizar um servidor proxy para acesso à Internet, certifique-se de que a instância de classificação do BlueXP  tem acesso de saída à Internet para contactar os seguintes endpoints.


TIP: Esta seção não é necessária para sistemas host instalados em sites sem conetividade com a Internet.

[cols="43,57"]
|===
| Endpoints | Finalidade 


| https://api.BlueXP .NetApp.com | Comunicação com o serviço BlueXP , que inclui contas NetApp. 


| https://NetApp-cloud-account.auth0.com \https://auth0.com | Comunicação com o site BlueXP  para autenticação centralizada de usuários. 


| https://support.compliance.api.BlueXP .NetApp.com/ \https://hub.docker.com \https://auth.docker.io \https://registry-1.docker.io \https://index.docker.io/ \https://dseasb33srnrn.cloudfront.net/ \https://production.cloudflare.docker.com/ | Fornece acesso a imagens de software, manifestos, modelos e para enviar logs e métricas. 


| https://support.compliance.api.BlueXP .NetApp.com/ | Permite que o NetApp transmita dados de Registros de auditoria. 


| \https://github.com/docker \https://download.docker.com | Fornece pacotes pré-requisitos para instalação do docker. 


| \http://packages.ubuntu.com/ \http://archive.ubuntu.com | Fornece pacotes pré-requisitos para instalação do Ubuntu. 
|===


== Verifique se todas as portas necessárias estão ativadas

Você deve garantir que todas as portas necessárias estejam abertas para comunicação entre o conetor, a classificação do BlueXP , o ative Directory e suas fontes de dados.

[cols="25,25,50"]
|===
| Tipo de ligação | Portas | Descrição 


| Conetor >> classificação BlueXP  | 8080 (TCP), 443 (TCP) e 80. 9000 | O firewall ou as regras de roteamento para o conetor devem permitir o tráfego de entrada e saída pela porta 443 de e para a instância de classificação BlueXP . Certifique-se de que a porta 8080 esteja aberta para que você possa ver o progresso da instalação no BlueXP . Se um firewall for usado no host Linux, a porta 9000 será necessária para processos internos dentro de um servidor Ubuntu. 


| Conetor do cluster do ONTAP (nas) | 443 (TCP)  a| 
O BlueXP  descobre clusters do ONTAP usando HTTPS. Se você usar políticas de firewall personalizadas, o host do conetor deve permitir o acesso HTTPS de saída através da porta 443. Se o conetor estiver na nuvem, toda a comunicação de saída é permitida pelo firewall predefinido ou pelas regras de roteamento.

|===


== Execute o script de pré-requisitos de classificação do BlueXP 

Siga estas etapas para executar o script de pré-requisitos de classificação do BlueXP .

https://youtu.be/_RCYpuLXiV0?si=QLGUw8mqPrz9qs4B["Assista a este vídeo"^] Para ver como executar o script pré-requisitos e interpretar os resultados.

.O que você vai precisar
* Verifique se o sistema Linux atende ao <<Verifique os requisitos do host,requisitos de host>>.
* Verifique se o sistema tem os dois pacotes de software pré-requisito instalados (Docker Engine ou Podman, e Python 3).
* Certifique-se de ter o root Privileges no sistema Linux.


.Passos
. Faça download do script de pré-requisitos de classificação do BlueXP  no https://mysupport.netapp.com/site/products/all/details/cloud-data-sense/downloads-tab/["Site de suporte da NetApp"^]. O arquivo que você deve selecionar é chamado *standalone-pre-required-tester-<version>*.
. Copie o arquivo para o host Linux que você pretende usar (usando `scp` ou algum outro método).
. Atribua permissões para executar o script.
+
[source, cli]
----
chmod +x standalone-pre-requisite-tester-v1.25.0
----
. Execute o script usando o seguinte comando.
+
[source, cli]
----
 ./standalone-pre-requisite-tester-v1.25.0 <--darksite>
----
+
Adicione a opção "--darksite" somente se você estiver executando o script em um host que não tem acesso à Internet. Certos testes pré-requisitos são ignorados quando o host não está conetado à internet.

. O script solicita o endereço IP da máquina host de classificação BlueXP .
+
** Introduza o endereço IP ou o nome do anfitrião.


. O script solicita se você tem um conetor BlueXP  instalado.
+
** Introduza *N* se não tiver um conetor instalado.
** Introduza *Y* se tiver um conetor instalado. E, em seguida, insira o endereço IP ou o nome do host do conetor BlueXP  para que o script de teste possa testar essa conetividade.


. O script executa uma variedade de testes no sistema e exibe resultados à medida que avança. Quando ele termina, ele grava um log da sessão em um arquivo chamado `prerequisites-test-<timestamp>.log` no diretório `/opt/netapp/install_logs`.


.Resultado
Se todos os testes pré-requisitos forem executados com sucesso, você poderá instalar a classificação BlueXP  no host quando estiver pronto.

Se algum problema foi descoberto, eles são categorizados como "recomendado" ou "obrigatório" para ser corrigido. Os problemas recomendados são tipicamente itens que fariam as tarefas de digitalização e categorização de classificação do BlueXP  serem executadas mais lentamente. Esses itens não precisam ser corrigidos - mas você pode querer abordá-los.

Se você tiver algum problema "necessário", você deve corrigir os problemas e executar o script de teste pré-requisitos novamente.
