= Versão 1,43
:allow-uri-read: 




=== Versão 1,43

Esta versão de classificação BlueXP  inclui:

.Priorizar exames de classificação
A classificação BlueXP  suporta a capacidade de priorizar exames de mapa e classificação, além de exames somente de mapeamento, permitindo selecionar quais exames são concluídos primeiro. A priorização dos exames de mapa e classificação é suportada durante e antes do início dos exames. Se optar por priorizar um exame enquanto este está em andamento, os exames de mapeamento e classificação são priorizados.

Para obter mais informações, link:task-managing-repo-scanning.html#prioritize-scans["Priorizar exames"]consulte .

.Suporte para categorias de dados de informações pessoais (PII) canadenses
As varreduras de classificação BlueXP  identificam categorias de dados de PII canadenses para informações bancárias, número de passaporte, número de seguro social e número de carteira de motorista e número de cartão de saúde para todas as províncias e territórios.

Para obter mais informações detalhadas, xref:reference-private-data-categories.adoc#types-of-personal-data[Categorias de dados pessoais]consulte .

.Classificação personalizada (pré-visualização)
A classificação BlueXP  suporta classificações personalizadas para exames de mapa e classificação. Com classificações personalizadas, você pode personalizar as digitalizações BlueXP  para capturar dados específicos da sua organização para garantir a conformidade com expressões regulares. Esta funcionalidade está atualmente em pré-visualização.

Para obter mais informações, xref:task-custom-classification.adoc[Adicione classificações personalizadas]consulte .

.Separador Pesquisas guardadas
A guia **políticas** foi renomeada xref:task-using-policies.html[**Pesquisas salvas**]. A funcionalidade é a mesma.

.Enviar eventos de digitalização para a linha do tempo do BlueXP 
A classificação BlueXP  suporta o envio de eventos de classificação (quando um exame é iniciado e quando termina) para o link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#audit-user-activity-from-the-bluexp-timeline["Linha do tempo de BlueXP "^].

.Atualizações de segurança
* O pacote keras foi atualizado, atenuando vulnerabilidades (BDSA-2025-0107 e BDSA-2025-1984).
* A configuração de contentores do Docker foi atualizada. O contentor não tem mais acesso às interfaces de rede do host para criar pacotes de rede brutos. Ao reduzir o acesso desnecessário, a atualização atenua potenciais riscos de segurança.


.Melhorias de performance
Melhorias de código foram implementadas para reduzir o uso de RAM e melhorar o desempenho geral da classificação BlueXP .

.Correções de bugs
Os bugs que fizeram com que as verificações do StorageGRID falhassem, as opções de filtro da página de investigação não carregassem e a avaliação de descoberta de dados não baixassem para avaliações de alto volume foram corrigidos.
