= Versão 1,45
:allow-uri-read: 




=== Versão 1,45

Esta versão de BlueXP classification inclui alterações de código que otimizam a utilização de recursos e:

.Fluxo de trabalho aprimorado para adicionar compartilhamentos de arquivos para digitalização
O fluxo de trabalho para adicionar compartilhamentos de arquivos a um grupo de compartilhamento de arquivos foi simplificado. O processo agora também diferencia o suporte ao protocolo CIFS com base no tipo de autenticação (Kerberos ou NTLM).

Para obter mais informações, link:https://docs.netapp.com/us-en/bluexp-classification/task-scanning-file-shares.html["Verificar compartilhamentos de arquivos"]consulte .

.Informações aprimoradas sobre o proprietário do arquivo
Agora você pode visualizar mais informações sobre os proprietários dos arquivos capturados na aba "Investigação". Ao visualizar metadados de um arquivo na guia Investigação, localize o proprietário do arquivo e selecione **Exibir detalhes** para ver o nome de usuário, o e-mail e o nome da conta SAM. Você também pode visualizar outros itens pertencentes a este usuário. Este recurso está disponível apenas para ambientes de trabalho com o Active Directory.

Para obter mais informações, link:https://docs.netapp.com/us-en/bluexp-classification/task-investigate-data.html["Investigue os dados armazenados em sua organização"]consulte .
