= Versão 1,40
:allow-uri-read: 




=== Versão 1,40

Esta versão de classificação do BlueXP  inclui as seguintes atualizações.

.Suporte para RHEL 9,5
Esta versão fornece suporte para Red Hat Enterprise Linux v9,5, além de versões anteriormente suportadas. Isso é aplicável a qualquer instalação manual no local da classificação do BlueXP , incluindo implantações em locais escuros.

Os sistemas operacionais a seguir requerem o uso do motor de contentor Podman, e eles exigem a classificação BlueXP  versão 1,30 ou superior: Red Hat Enterprise Linux versão 8,8, 8,10, 9,0, 9,1, 9,2, 9,3, 9,4 e 9,5.

.Priorizar exames
Ao digitalizar a configuração, você pode priorizar as digitalizações mais importantes para que elas sejam feitas antes de outras digitalizações. Este recurso ajuda quando você tem muitos ambientes de trabalho e você deseja garantir que as verificações de alta prioridade estão sendo feitas com sucesso no início.

Existem dois tipos de digitalizações:

* *As digitalizações somente de mapeamento* fornecem apenas uma visão geral de alto nível de seus dados. O mapeamento pode ser feito em suas fontes de dados muito rapidamente, porque não acessa arquivos para ver os dados dentro.
* *Map e Classify* digitalizações fornecem varredura de nível profundo de seus dados.


Você pode se beneficiar do uso de varreduras somente de mapeamento para verificar rapidamente seus dados para identificar as fontes de dados que exigem mais pesquisas e, em seguida, ativar o mapa e classificar varreduras somente nas fontes de dados ou volumes necessários.

A prioridade é atribuída apenas a digitalizações só de mapeamento, e não a mapear e classificar digitalizações.

A prioridade é definida como 1 por padrão, e você pode alterá-la para qualquer número entre 1 e 10. Quanto menor o número, maior a prioridade. Se você não definir uma prioridade, a digitalização recebe uma prioridade de 5.

Para alterar a prioridade, faça o seguinte:

. No menu classificação BlueXP , selecione *Configuração*.
. Selecione os recursos que deseja priorizar.
. Na opção ações ..., selecione *priorizar a digitalização*.


.Tente novamente as digitalizações
Com esta versão, você pode tentar novamente digitalizações que falharam. Este recurso é útil quando você tem uma varredura que falhou devido a um problema temporário, como uma interrupção da rede. Pode tentar novamente a digitalização sem ter de a reconfigurar.

Para tentar novamente uma digitalização, faça o seguinte:

. No menu classificação BlueXP , selecione *Configuração*.
. Execute um dos seguintes procedimentos:
+
** Para tentar novamente todas as digitalizações com falha, selecione *Repetir todas as digitalizações*.
** Para tentar novamente uma digitalização específica, selecione o recurso e selecione *Repetir digitalização* na opção ações ....




A digitalização é novamente testada com a mesma configuração que a digitalização original. Se a digitalização falhar novamente, pode tentar novamente quantas vezes for necessário.
