= Versão 1,42
:allow-uri-read: 




=== Versão 1,42

Esta versão de classificação BlueXP  inclui:

.Digitalização em massa para ambientes de trabalho
A classificação BlueXP  suporta operações em massa para ambientes de trabalho. Pode optar por ativar Mapeamento de digitalizações, ativar mapa e classificar digitalizações, desativar digitalizações ou criar uma configuração personalizada entre volumes no ambiente de trabalho. Se você fizer uma seleção para um volume individual, ele substituirá a seleção em massa. Para executar uma operação em massa, navegue até a página **Configuração** e faça a sua seleção.

.Baixe o relatório de investigação localmente
A classificação BlueXP  suporta a capacidade de transferir relatórios de investigação de dados localmente para visualização no navegador. Se você escolher a opção local, a investigação de dados estará disponível apenas no formato CSV e exibirá apenas as primeiras 10.000 linhas de dados.

Para obter mais informações, link:task-investigate-data.html#create-the-data-investigation-report["Investigue os dados armazenados na sua organização com a classificação BlueXP "]consulte .
